title: Sharif University of Technology - Machine Learning Course - Fall 2023
description: This webpage will contain all the news and information about the machine learning course taught by Dr. Motahari on Fall 2023.
theme: just-the-docs

url: https://sharif-ml.github.io

aux_links:
  Template Repository: https://github.com/sharif-ml/just-the-docs-template

plugins:
  - jekyll-default-layout